### ISSUE TITLE
near payments 설치시 vitest 정상동작 하지 않는 현상

### ISSUE THREAD

**Issue by Gn0lee** [bytrustu/near-payments#1]
## 이슈 및 개선요청

near payment import 후 vitest 실행시 import 관련 에러가 발생합니다.

## 스크린샷

![image](https://github.com/bytrustu/near-payments/assets/93526602/1bdf1f84-3451-4a15-a82b-2c668878d6b7)

## 코멘트

```
Error: Directory import '/Users/jinho/project/react-shopping-cart/node_modules/near-payments/dist/payments' is not supported resolving ES modules imported from /Users/jinho/project/react-shopping-cart/node_modules/near-payments/dist/index.js
```

**Comment by Gn0lee** [comment]
```
// node_modules/near-payments/dist/payments/index.js

export * from './components/index.js';
export * from './constants/index.js';
export * from './hooks/index.js';
export * from './form/index.js';
export * from './providers/index.js';
export * from './types/index.js';
export * from './utils/index.js';

```

이런식으로 파일명을 직접 바라보도록 수정하니 정상동작하네요.

**Comment by bytrustu** [comment]
@Gn0lee 
이슈내용 공유주셔서 감사합니다! 😊
전달주신 내용 개선해서 **0.1.10** 버전으로 배포했습니다.

## vitest file import 이슈

- 개선 전
![image](https://github.com/bytrustu/near-payments/assets/39726717/382579d4-f41a-4d9b-977b-758d5eeb7839)

- 개선 후
![image](https://github.com/bytrustu/near-payments/assets/39726717/867d1e71-e60e-4a5e-a8cb-337208ff1636)


## TextField type password font 이슈

![image](https://github.com/bytrustu/near-payments/assets/39726717/2b515085-40e4-4a81-b86d-ef226d02997f)

**Comment by Gn0lee** [comment]
감사합니다!!
